// <auto-generated />
namespace LoginService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class somechange2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(somechange2));
        
        string IMigrationMetadata.Id
        {
            get { return "202012111244453_somechange2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
